### PR TITLE
Adding new package knowrob_uwsim for Underwater Simulation

### PR DESCRIPTION
**Pull request by svenkatachalam**
Prolog files and OWL file for UWSim execution. Added the package knowrob_uwsim.

### CODE REVIEW

**Comment by asilx** [comment]
What does ActionID paramater do in your predicates? Most of them do not use this parameter at all.

**Comment by svenkatachalam** [comment]
Hello Asil,

I have removed the ActionID parameter for the predicates that don't require any input arguments.

**Comment by daniel86** [comment]
Well this ticket is here since more then a year now.
@asilx should it be merged or rejected?
I don't know at all what UWSim is, to be honest.

**Comment by daniel86** [comment]
no answer for a week, closing for now

**Pull request closed without merging**
